// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	model "github.com/Blackmamba23/cars-fleet-service/pkg/model"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// GetCarByName provides a mock function with given fields: carName
func (_m *Repository) GetCarByName(carName string) (model.Car, error) {
	ret := _m.Called(carName)

	var r0 model.Car
	if rf, ok := ret.Get(0).(func(string) model.Car); ok {
		r0 = rf(carName)
	} else {
		r0 = ret.Get(0).(model.Car)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(carName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCarsByName provides a mock function with given fields: carName
func (_m *Repository) GetCarsByName(carName string) ([]model.Car, error) {
	ret := _m.Called(carName)

	var r0 []model.Car
	if rf, ok := ret.Get(0).(func(string) []model.Car); ok {
		r0 = rf(carName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Car)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(carName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t mockConstructorTestingTNewRepository) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
